fix: running tests
fabiendv/daskeyboard-applet--discourse pull request #1
Opened 2020-12-29 18:39 UTC by matthieulapatate

Writing test for every situation cases

2020-12-30 17:23 UTC, fabiendv requested changes

2020-12-30 17:23 UTC, fabiendv commented on .eslintrc.js
> +};
Why did you choose this configuration?

2020-12-30 17:23 UTC, fabiendv commented on .prettierrc.json
> +}
Do not push empty file

2020-12-30 17:23 UTC, fabiendv commented on test/response-mook1.json
> +{
Put a real name instead of numbers
eg: response-mook-user-tasks

2020-12-30 19:13 UTC, fabiendv requested changes
- [ ]  Set up hard and confusing. (API username?) README and questions/help into the configuration need to be updated

- [x]  The applet should not send signal when no notifications. Send a signal only if smth happened.

- [ ]  All code errors (`cannot read property of undefined`) must be prevent by english langage (eg. `Ouups. Please check the configuration`)

- [ ]  I would prefer calling this applet Discourse and saying into the README that only admins can use it. 

- [ ] The image should be the same size and border than Asana's applet. (You can find a good example of README as well)

- [ ] Maybe explain how to set up admin key (or a link) because it's too hard (with too much config)

- [ ]  Update description `Make blinking key...` :> Look at Asana

- [ ]  Update displayName :> `Discourse`

2021-01-05 11:54 UTC, Mubramaj requested changes

2021-01-05 11:54 UTC, Mubramaj commented on index.js
> +                        url:
Could use \`${host}/u/${this.config.username}/notifications?filter=unread\` easier to read

2021-01-05 11:54 UTC, Mubramaj commented on index.js
> +    // main function running
This is not the right format for a js method comment

2021-01-05 11:54 UTC, Mubramaj commented on package.json
> +        "dotenv": "^8.2.0",
Why do you need dotenv ?

2021-01-05 11:54 UTC, Mubramaj commented on test/response-mook-1-notif.json
> +    "notifications": [
Name of file should be more explicit `response-mook-1` not working.

Example of good name -> goodResponseWith2NotificationsMock

2021-01-05 13:53 UTC, fabiendv commented
- [ ] Not working without entering http
- [ ] Removed API Key usename (unused)
- [ ] mysuperusername becomes johnDoe

2021-01-05 14:03 UTC, fabiendv commented
- [ ] click `show in Discourse` go to blank link

2021-01-05 14:18 UTC, fabiendv commented
- [ ] dotenv has been removed. But not into `yarn.lock`. Please delete the file and run yarn again.
- [ ] icon size should be 512x512
- [ ] image should be updated (same layout than Asana's)

2021-01-05 14:23 UTC, fabiendv commented
- [ ] When adding API key. The link goes to github : update to `<your-forum-url>.com/admin`. I admit the solution is not good and ugly, but a github link is worst because the repo can be deleted and the user won't have an easy help.

2021-01-05 14:30 UTC, fabiendv commented
Readme:

- [ ] title is not standard. Please check Asana.
- [ ] should respect MDlint
- [ ] first paragraph is even to readme_end_user

2021-01-06 11:40 UTC, fabiendv requested changes

2021-01-06 11:40 UTC, fabiendv commented on package.json
> +            "supportUrl": "<your-forum-url>.com/admin"
Add https.
+ Add go to <your-forum-url> into the hint

2021-01-06 11:43 UTC, fabiendv commented
- [ ] Update tests to make them pass
- [ ] Prevent `notifications of undefined` error when user enter a bad forum url.
- [ ] Popup link is not working : Maybe you can add `https://` before `${host}

2021-01-06 16:20 UTC, merged